export {
  CONCAT_TYPE,
  concat,
  type ConcatResult,
  DEFAULT_VALUE_TYPE,
  defaultValue,
  type DefaultValueResult,
  FIND_ALL_TYPE,
  FIND_TYPE,
  find,
  findAll,
  type FindAllResult,
  type FindResult,
  JSON_TO_TABLE_TYPE,
  jsonToAsciiTable,
  type JsonToTableResult,
  REPLACE_TYPE,
  replace,
  type ReplaceResult,
  SLUGIFY_TYPE,
  slugify,
  type SlugifyResult,
  SPLIT_TYPE,
  split,
  type SplitResult,
  STRIP_HTML_TYPE,
  stripHtml,
  type StripHtmlResult,
} from './text';

import {
  concat,
  defaultValue,
  find,
  findAll,
  jsonToAsciiTable,
  replace,
  slugify,
  split,
  stripHtml,
} from './text';

/** Every Text action, for catalog builds and registration. */
export const textActions = [
  concat,
  replace,
  split,
  find,
  findAll,
  slugify,
  defaultValue,
  stripHtml,
  jsonToAsciiTable,
] as const;
